### ISSUE TITLE
Would be nice to play a sound

### ISSUE THREAD

**Issue by RobertCordingly** [fatfingers23/mac-runelite-native-notifications#1]
This plugin is great! I wish it had the option to play a sound with notifications. Sometimes I'm really not playing attention and don't see the popup

**Comment by fatfingers23** [comment]
Hey, glad you like it! Sounds should be working. It uses Runelite settings for sound, so make sure that is set on under RuneLite > Notification Settings > Notification sound.  If that is checked may check under sounds in your mac settings and make sure "Play sound effects through" is selected to your output device, this one gets me a lot.

**Comment by fatfingers23** [comment]
This should be handled by native RuneLite notification settings. Closing cause was not able to recreate.
