### ISSUE TITLE
Shutdown switching windows and mac

### ISSUE THREAD

**Issue by miranro** [fatfingers23/mac-runelite-native-notifications#2]
Hi,

First of all thanks for the plugin! I checked and see you stop the plugin if the OS is not mac. This is quite annoying for me since I have a macbook and windows desktop and have to re-enable the plugin every time I played on the desktop. 

Might be an option to do the check around the notification send instead to fix this issue. I'm willing to make a PR if you agree with this solution.

**Comment by fatfingers23** [comment]
Hey! Sorry missed this issue. I'm glad you enjoy the plugin! 

I had actually started to implement this back in august but never submitted it. If you'd like to look at how I did mine, or try another solution you have I'd welcome any pr that solves the problem well!

Here's what I have. Note it's not been tested much and been a while. https://github.com/fatfingers23/mac-runelite-native-notifications/commit/586d92e291e662c4f355e3c0ee83b281e50543a6

**Comment by fatfingers23** [comment]
Added this update in the above PR. You should now check if it's a Mac OS on notification instead of just turning off the plugin if not. Should also try to toggle tray notifications off so you can have notifications work seamlessly in both os
