### ISSUE TITLE
Send notifications when focused option

### ISSUE THREAD

**Issue by danieltaylor** [fatfingers23/mac-runelite-native-notifications#4]
The default notification system has an option to suppress notifications when RuneLite is in focus.  It would be great if this plugin could either adjust its behavior to do the same based on RuneLite's current settings, or have a similar option in its own plugin settings.

**Comment by fatfingers23** [comment]
Was the motivation i needed to finally clean up the code i had in the back log for this! Thank you for raising the issue. I have a PR in to get this out. I'll close the issue once it merges.

**Comment by danieltaylor** [comment]
Wow, what an impressive response time!  Thank you 😊

**Comment by fatfingers23** [comment]
Thank you! The problem should be resolved and live now. just may need to restart RuneLite if it's been left up.

**Comment by danieltaylor** [comment]
It's working great!  Thanks for updating!
